# Pipeline de CI/CD para construir uma imagem Docker e enviá-la para o Azure Container Registry (ACR)

trigger:
- main  # O pipeline será acionado por pushes na branch 'main'

resources:
- repo: self

variables:
  # --- ATENÇÃO: ATUALIZE ESTAS VARIÁVEIS NO AZURE DEVOPS ---

  # Nome da Conexão de Serviço da sua assinatura Azure no Azure DevOps
  azureSubscription: 'SUA_AZURE_SUBSCRIPTION_SERVICE_CONNECTION' 
  
  # Nome do seu Grupo de Recursos no Azure (ex: 'DIO-API-DEMO')
  resourceGroup: 'SEU_RESOURCE_GROUP' 
  
  # URL do seu Container Registry (ex: 'acrapaulo.azurecr.io'). Precisa ser um nome único globalmente.
  containerRegistry: 'SEU_CONTAINER_REGISTRY.azurecr.io' 
  
  # Nome do repositório de imagem dentro do seu registry (ex: 'apitempo')
  imageRepository: 'apitempo' 
  
  # Caminho para o seu Dockerfile.
  dockerfilePath: '$(Build.SourcesDirectory)/APITempo/Dockerfile' 
  
  # Tag da imagem, usando o ID do Build para garantir que seja única
  tag: '$(Build.BuildId)'
  
  # Máquina virtual que executará o pipeline
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and Push Docker Image
  jobs:
  - job: Build
    displayName: Build Job
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: 'Build e Push da imagem para o ACR'
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        # Nome da Conexão de Serviço do tipo 'Azure Container Registry' no Azure DevOps
        containerRegistry: $(containerRegistry)
        tags: |
          $(tag)
